### ISSUE TITLE
AspNetCore update

### ISSUE THREAD

**Issue by stephenstroud** [cady-io/hangfire-ravendb#6]
Any plans to update this project to AspNet-Core?

**Comment by AustinWinstanley** [comment]
We can look at the dependencies. As long as they all support core, we should be able to. Will get back to you on this.

**Comment by stephenstroud** [comment]
Ok sounds great, wondering if it would be good to decouple the dependency on SqlServer too, is it needed? I'm happy to contribute again.

**Comment by AustinWinstanley** [comment]
Decoupling the dependency on Sql is a good idea @stephenstroud and we'd be happy to have your help. Not sure when we'd be able to get to this. If you make a pull request we'll definitely implement it.

**Comment by stephenstroud** [comment]
Sure okay, Ill start by updating the project to core, might be able to create a PR by end of next week.

**Comment by AustinWinstanley** [comment]
Upgraded to .Net Core and pushed to Nuget

https://www.nuget.org/packages/Hangfire.Raven/2.0.0
