### ISSUE TITLE
Dashboard not working yet

### ISSUE THREAD

**Issue by camhart** [cady-io/hangfire-ravendb#7]
```
using Hangfire;
using HangFire.Raven.Storage;
using Microsoft.Owin;
using Owin;

[assembly: OwinStartupAttribute(typeof(HangfireServer.Startup))]
namespace HangfireServer
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
            GlobalConfiguration.Configuration.UseRavenStorage("http://localhost:8080", "hangfire");
            app.UseHangfireDashboard();
            app.UseHangfireServer();
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/3038809/13717858/62aee29e-e799-11e5-9dee-4e46494d8419.png)

Any ideas why?  A database titled "hangfire" does exist and the ravendb server is running at http://localhost:8080.

**Comment by AndrewMarkley** [comment]
I don't know that the dashboard ever worked. We were not using it in our application.

**Comment by krivulcik** [comment]
Hangfire itself (queuing, scheduling and processing of background jobs) does work correctly with RavenDB, we have used it for about half a year now in production. However, some features don't work and the dashboard is one of them. RavenDB storage implementation doesn't implement some parts, in this case the RavenStorage.GetMonitoringApi method returns null in https://github.com/cady-io/hangfire-ravendb/blob/master/src/Hangfire.Raven/Storage/RavenStorage.cs#L62 .

**Comment by Sphiecoh** [comment]
After merging in [#9](https://github.com/cady-io/hangfire-ravendb/pull/9) this is no longer the case.
RavenStorage.GetMonitoringApi is now implemented.

**Comment by AustinWinstanley** [comment]
I will look at getting the Dashboard working now that @Sphiecoh got RavenStorage.GetMonitoringApi working. Not sure a timeline yet.

**Comment by xinix00** [comment]
Is it still not working? Did I forgot to commit something? It's depending on one index to get the statistics needed to display on the page. 
    public class MyRestrictiveAuthorizationFilter 
        : IDashboardAuthorizationFilter
    {
        public bool Authorize([NotNull] DashboardContext context)
        {
            return true;
        }
    }

Though you should add:

            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
                Authorization = new[] { new MyRestrictiveAuthorizationFilter() }
            });

**Comment by AustinWinstanley** [comment]
Ok, have a working version in an AspNetCore project with the Dashboard working. Will be released soon with an example project.
